extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_f3dlite_material_012_lights;
extern u8 ccm_dl_woodthing_ci4[];
extern u8 ccm_dl_woodthing_pal_rgba16[];
extern u8 ccm_dl_contrasty_rock_ci8[];
extern u8 ccm_dl_contrasty_rock_pal_rgba16[];
extern u8 ccm_dl_awsome_stone_ci8[];
extern u8 ccm_dl_awsome_stone_pal_rgba16[];
extern Vtx ccm_dl_bridge_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_bridge_mesh_layer_1_vtx_0[88];
extern Gfx ccm_dl_bridge_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_cliff1_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_cliff1_mesh_layer_1_vtx_0[79];
extern Gfx ccm_dl_cliff1_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_cliff1_mesh_layer_1_vtx_1[69];
extern Gfx ccm_dl_cliff1_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_death_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_death_mesh_layer_1_vtx_0[25];
extern Gfx ccm_dl_death_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_hut_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_hut_mesh_layer_1_vtx_0[171];
extern Gfx ccm_dl_hut_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_hut_mesh_layer_1_vtx_1[63];
extern Gfx ccm_dl_hut_mesh_layer_1_tri_1[];
extern Gfx mat_ccm_dl_f3dlite_material[];
extern Gfx mat_revert_ccm_dl_f3dlite_material[];
extern Gfx mat_ccm_dl_f3dlite_material_001[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_001[];
extern Gfx mat_ccm_dl_f3dlite_material_002[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_002[];
extern Gfx mat_ccm_dl_f3dlite_material_012[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_012[];
extern Gfx mat_ccm_dl_f3dlite_material_011[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_011[];
extern Gfx ccm_dl_bridge_mesh_layer_1[];
extern Gfx ccm_dl_cliff1_mesh_layer_1[];
extern Gfx ccm_dl_death_mesh_layer_1[];
extern Gfx ccm_dl_hut_mesh_layer_1[];
