extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_Wall_Upper_lights;
extern Lights1 castle_grounds_dl_Floor_Upper_lights;
extern Lights1 castle_grounds_dl_Stairs_lights;
extern Lights1 castle_grounds_dl_Floor_Lower_lights;
extern Lights1 castle_grounds_dl_Wall_Lower_lights;
extern Lights1 castle_grounds_dl_Pillar_lights;
extern Lights1 castle_grounds_dl_Rim_lights;
extern u8 castle_grounds_dl_hub_tile_floor_ci8[];
extern u8 castle_grounds_dl_hub_tile_floor_pal_rgba16[];
extern u8 castle_grounds_dl_hud_wooden_floor_ci8[];
extern u8 castle_grounds_dl_hud_wooden_floor_pal_rgba16[];
extern Vtx castle_grounds_dl_Cylinder_003_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cylinder_003_mesh_layer_1_vtx_0[430];
extern Gfx castle_grounds_dl_Cylinder_003_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cylinder_003_mesh_layer_1_vtx_1[96];
extern Gfx castle_grounds_dl_Cylinder_003_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Cylinder_003_mesh_layer_1_vtx_2[9];
extern Gfx castle_grounds_dl_Cylinder_003_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_Cylinder_003_mesh_layer_1_vtx_3[16];
extern Gfx castle_grounds_dl_Cylinder_003_mesh_layer_1_tri_3[];
extern Vtx castle_grounds_dl_Cylinder_003_mesh_layer_1_vtx_4[22];
extern Gfx castle_grounds_dl_Cylinder_003_mesh_layer_1_tri_4[];
extern Vtx castle_grounds_dl_Cylinder_003_mesh_layer_1_vtx_5[196];
extern Gfx castle_grounds_dl_Cylinder_003_mesh_layer_1_tri_5[];
extern Vtx castle_grounds_dl_Cylinder_003_mesh_layer_1_vtx_6[124];
extern Gfx castle_grounds_dl_Cylinder_003_mesh_layer_1_tri_6[];
extern Gfx mat_castle_grounds_dl_Wall_Upper[];
extern Gfx mat_revert_castle_grounds_dl_Wall_Upper[];
extern Gfx mat_castle_grounds_dl_Floor_Upper[];
extern Gfx mat_revert_castle_grounds_dl_Floor_Upper[];
extern Gfx mat_castle_grounds_dl_Stairs[];
extern Gfx mat_revert_castle_grounds_dl_Stairs[];
extern Gfx mat_castle_grounds_dl_Floor_Lower[];
extern Gfx mat_revert_castle_grounds_dl_Floor_Lower[];
extern Gfx mat_castle_grounds_dl_Wall_Lower[];
extern Gfx mat_revert_castle_grounds_dl_Wall_Lower[];
extern Gfx mat_castle_grounds_dl_Pillar[];
extern Gfx mat_revert_castle_grounds_dl_Pillar[];
extern Gfx mat_castle_grounds_dl_Rim[];
extern Gfx mat_revert_castle_grounds_dl_Rim[];
extern Gfx castle_grounds_dl_Cylinder_003_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
