const GeoLayout painting_custom_Switch_State_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, painting_custom_Other_mesh_layer_1_mat_override_Painting_TTM_0),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, painting_custom_SemiInsidePart_mesh_layer_1_mat_override_Painting_TTM_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout painting_custom_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 166, 100),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_painting_switch_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, painting_custom_Other_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, painting_custom_SemiInsidePart_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, painting_custom_Switch_State_opt1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
