const GeoLayout treetoplevelplatform_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 217, 350),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, treetoplevelplatform_MainPart_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 83, -548, -1, treetoplevelplatform_Cog1_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -100, -547, -6, treetoplevelplatform_Cog2_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, treetoplevelplatform_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
