extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern const GeoLayout lll_area_2_geo[];
extern const GeoLayout lll_area_2[];
extern const Collision lll_area_2_collision[];
extern const MacroObject lll_area_2_macro_objs[];
extern Lights1 lll_dl_leaves_lights;
extern Lights1 lll_dl_grass_lights;
extern Lights1 lll_dl_dirt_lights;
extern Lights1 lll_dl_tree_wood_lights;
extern Lights1 lll_dl_wing_cap_tree_wood_warp_UNUSED_lights;
extern Lights1 lll_dl_sm64_water_mat_lights;
extern Lights1 lll_dl_hot_hot_hot___lights;
extern Lights1 lll_dl_metal_gate_lights;
extern Lights1 lll_dl_lava_rock_lights;
extern Lights1 lll_dl_basic_rock_lights;
extern u8 lll_dl_leaves_rgba16[];
extern u8 lll_dl_grass_rgba16[];
extern u8 lll_dl_dirt_rgba16[];
extern u8 lll_dl_tree_rgba16[];
extern u8 lll_dl_lava_rock_rgba16[];
extern u8 lll_dl_darker_inside_rock_rgba16[];
extern Vtx lll_dl_Leaves_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Leaves_mesh_layer_1_vtx_0[180];
extern Gfx lll_dl_Leaves_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_0[308];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_1[4];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_2[376];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_3[7];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_3[];
extern Vtx lll_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx lll_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx lll_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_1_vtx_0[4];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_1_vtx_1[21];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_1_vtx_2[237];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_1_tri_2[];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_1_vtx_3[92];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_1_tri_3[];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_4_vtx_cull[8];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_4_vtx_0[6];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_4_tri_0[];
extern Vtx lll_dl_Log_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Log_mesh_layer_1_vtx_0[107];
extern Gfx lll_dl_Log_mesh_layer_1_tri_0[];
extern Gfx mat_lll_dl_leaves[];
extern Gfx mat_revert_lll_dl_leaves[];
extern Gfx mat_lll_dl_grass[];
extern Gfx mat_revert_lll_dl_grass[];
extern Gfx mat_lll_dl_dirt[];
extern Gfx mat_revert_lll_dl_dirt[];
extern Gfx mat_lll_dl_tree_wood[];
extern Gfx mat_revert_lll_dl_tree_wood[];
extern Gfx mat_lll_dl_wing_cap_tree_wood_warp_UNUSED[];
extern Gfx mat_revert_lll_dl_wing_cap_tree_wood_warp_UNUSED[];
extern Gfx mat_lll_dl_sm64_water_mat[];
extern Gfx mat_revert_lll_dl_sm64_water_mat[];
extern Gfx mat_lll_dl_hot_hot_hot__[];
extern Gfx mat_revert_lll_dl_hot_hot_hot__[];
extern Gfx mat_lll_dl_metal_gate[];
extern Gfx mat_revert_lll_dl_metal_gate[];
extern Gfx mat_lll_dl_lava_rock[];
extern Gfx mat_revert_lll_dl_lava_rock[];
extern Gfx mat_lll_dl_basic_rock[];
extern Gfx mat_revert_lll_dl_basic_rock[];
extern Gfx lll_dl_Leaves_mesh_layer_1[];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1[];
extern Gfx lll_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_1[];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_4[];
extern Gfx lll_dl_Log_mesh_layer_1[];
