extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern const GeoLayout lll_area_2_geo[];
extern const GeoLayout lll_area_2[];
extern const Collision lll_area_2_collision[];
extern const MacroObject lll_area_2_macro_objs[];
extern Lights1 lll_dl_grass_lights;
extern Lights1 lll_dl_dirt_lights;
extern Lights1 lll_dl_tree_wood_lights;
extern Lights1 lll_dl_leaves_lights;
extern Lights1 lll_dl_sm64_water_mat_lights;
extern Lights1 lll_dl_hot_hot_hot___lights;
extern u8 lll_dl_grass_rgba16[];
extern u8 lll_dl_dirt_rgba16[];
extern u8 lll_dl_tree_rgba16[];
extern u8 lll_dl_leaves_rgba16[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_0[165];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_1[4];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_2[358];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_3[180];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_3[];
extern Vtx lll_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx lll_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx lll_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_1_vtx_0[133];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Level_Mesh_2_mesh_layer_1_vtx_1[58];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Log_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Log_mesh_layer_1_vtx_0[107];
extern Gfx lll_dl_Log_mesh_layer_1_tri_0[];
extern Gfx mat_lll_dl_grass[];
extern Gfx mat_revert_lll_dl_grass[];
extern Gfx mat_lll_dl_dirt[];
extern Gfx mat_revert_lll_dl_dirt[];
extern Gfx mat_lll_dl_tree_wood[];
extern Gfx mat_revert_lll_dl_tree_wood[];
extern Gfx mat_lll_dl_leaves[];
extern Gfx mat_revert_lll_dl_leaves[];
extern Gfx mat_lll_dl_sm64_water_mat[];
extern Gfx mat_revert_lll_dl_sm64_water_mat[];
extern Gfx mat_lll_dl_hot_hot_hot__[];
extern Gfx mat_revert_lll_dl_hot_hot_hot__[];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1[];
extern Gfx lll_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx lll_dl_Level_Mesh_2_mesh_layer_1[];
extern Gfx lll_dl_Log_mesh_layer_1[];
