extern const GeoLayout thi_area_1_geo[];
extern const GeoLayout thi_area_1[];
extern const Collision thi_area_1_collision[];
extern const MacroObject thi_area_1_macro_objs[];
extern Lights1 thi_dl_Grass_layer1_lights;
extern Lights1 thi_dl_Dirt__Slippery__layer1_lights;
extern Lights1 thi_dl_Sand_layer1_lights;
extern Lights1 thi_dl_Dirt__Walkable__layer1_lights;
extern Lights1 thi_dl_sm64_water_mat_lights;
extern u8 thi_dl_grass2_ci8[];
extern u8 thi_dl_grass2_pal_rgba16[];
extern u8 thi_dl_dirt3_ci8[];
extern u8 thi_dl_dirt3_pal_rgba16[];
extern u8 thi_dl_sand_ci8[];
extern u8 thi_dl_sand_pal_rgba16[];
extern u8 thi_dl_water_ci8[];
extern u8 thi_dl_water_pal_rgba16[];
extern Vtx thi_dl_Vert_mesh_layer_1_vtx_cull[8];
extern Vtx thi_dl_Vert_mesh_layer_1_vtx_0[106];
extern Gfx thi_dl_Vert_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Vert_mesh_layer_1_vtx_1[277];
extern Gfx thi_dl_Vert_mesh_layer_1_tri_1[];
extern Vtx thi_dl_Vert_mesh_layer_1_vtx_2[53];
extern Gfx thi_dl_Vert_mesh_layer_1_tri_2[];
extern Vtx thi_dl_Vert_mesh_layer_1_vtx_3[12];
extern Gfx thi_dl_Vert_mesh_layer_1_tri_3[];
extern Vtx thi_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx thi_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx thi_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Gfx mat_thi_dl_Grass_layer1[];
extern Gfx mat_revert_thi_dl_Grass_layer1[];
extern Gfx mat_thi_dl_Dirt__Slippery__layer1[];
extern Gfx mat_revert_thi_dl_Dirt__Slippery__layer1[];
extern Gfx mat_thi_dl_Sand_layer1[];
extern Gfx mat_revert_thi_dl_Sand_layer1[];
extern Gfx mat_thi_dl_Dirt__Walkable__layer1[];
extern Gfx mat_revert_thi_dl_Dirt__Walkable__layer1[];
extern Gfx mat_thi_dl_sm64_water_mat[];
extern Gfx mat_revert_thi_dl_sm64_water_mat[];
extern Gfx thi_dl_Vert_mesh_layer_1[];
extern Gfx thi_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx thi_dl_material_revert_render_settings[];
